apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secret
  namespace: ${NAMESPACE}
type: Opaque
data:
  DATABASE_USERNAME: ''
  DATABASE_PASSWORD: ''
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${CONTAINER_IMAGE}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DATABASE_ENGINE
            value: sqlite3
          - name: DATABASE_NAME
            value: 'notejam.db'
          - name: DATABASE_HOST
            value: ''
          - name: DATABASE_PORT
            value: ''
        envFrom:
          - secretRef:
              name: ${APP_NAME}-secret
        ports:
        - containerPort: ${CONTAINER_PORT}

