apiVersion: v1
kind: Namespace
metadata:
  name: prd-django-notejam
---
apiVersion: v1
kind: Namespace
metadata:
  name: stg-django-notejam
---
apiVersion: v1
kind: Secret
metadata:
  name: django-notejam-secret
  namespace: prd-django-notejam
type: Opaque
data:
  DATABASE_USERNAME: <USERNAME>
  DATABASE_PASSWORD: <PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: django-notejam-db-secret
  namespace: prd-django-notejam
type: Opaque
data:
  POSTGRES_USER: <USERNAME>
  POSTGRES_PASSWORD: <PASSWORD>